name: CI

on:
  push:
    branches: [ "master", "php8" ]
  pull_request:
    branches: [ "master", "php8" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.4']

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: json
        coverage: pcov
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --memory-limit=512M --error-format=github

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit --coverage-text

    - name: Test server startup
      run: timeout 3 php cmd.php --debug 1 || [ $? -eq 124 ]
